import type { Application } from '@/types/application'

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    company: 'Vercel',
    role: 'Product Designer',
    contractType: 'cdi',
    appliedAt: '2026-05-18',
    offerUrl: 'https://vercel.com/careers',
    status: 'interview',
    notes: 'Préparer un portfolio centré sur design systems et accessibilité.',
    history: [
      {
        id: 'h1',
        date: '2026-05-18T10:00:00',
        message: 'Candidature enregistrée',
      },
      {
        id: 'h2',
        date: '2026-05-19T14:22:00',
        message: 'Email de confirmation reçu',
      },
      {
        id: 'h3',
        date: '2026-05-19T16:05:00',
        message: 'Entretien planifié avec le hiring manager',
      },
    ],
  },
  {
    id: '2',
    company: 'Linear',
    role: 'Frontend Engineer',
    contractType: 'cdi',
    appliedAt: '2026-05-16',
    offerUrl: 'https://linear.app/careers',
    status: 'sent',
    notes: 'Mettre en avant TypeScript et performance runtime.',
    history: [
      { id: 'h1', date: '2026-05-16T09:12:00', message: 'Candidature envoyée' },
      { id: 'h2', date: '2026-05-16T09:30:00', message: 'Accusé de réception' },
    ],
  },
  {
    id: '3',
    company: 'Notion',
    role: 'Growth Marketing',
    contractType: 'cdd',
    appliedAt: '2026-05-12',
    offerUrl: 'https://www.notion.so/careers',
    status: 'rejected',
    notes: 'Bonne préparation mais profil plus senior recherché.',
    history: [
      { id: 'h1', date: '2026-05-12T11:00:00', message: 'Candidature envoyée' },
      { id: 'h2', date: '2026-05-14T08:45:00', message: 'Refus après revue CV' },
    ],
  },
  {
    id: '4',
    company: 'Stripe',
    role: 'Developer Advocate',
    contractType: 'cdi',
    appliedAt: '2026-05-10',
    offerUrl: 'https://stripe.com/jobs',
    status: 'accepted',
    notes: 'Offre reçue — négociation salaire en cours.',
    history: [
      { id: 'h1', date: '2026-05-10T15:20:00', message: 'Candidature envoyée' },
      { id: 'h2', date: '2026-05-11T10:00:00', message: 'Entretien technique validé' },
      { id: 'h3', date: '2026-05-13T17:30:00', message: 'Offre d’emploi reçue' },
    ],
  },
  {
    id: '5',
    company: 'Figma',
    role: 'Design Engineer',
    contractType: 'cdi',
    appliedAt: '2026-05-08',
    offerUrl: 'https://www.figma.com/careers',
    status: 'to_send',
    notes: 'Finaliser la lettre de motivation avant envoi.',
    history: [{ id: 'h1', date: '2026-05-08T18:00:00', message: 'Brouillon créé' }],
  },
  {
    id: '6',
    company: 'Supabase',
    role: 'Solutions Engineer',
    contractType: 'freelance',
    appliedAt: '2026-05-05',
    offerUrl: 'https://supabase.com/careers',
    status: 'interview',
    notes: 'Focus sur Postgres et intégrations temps réel.',
    history: [
      { id: 'h1', date: '2026-05-05T12:00:00', message: 'Candidature envoyée' },
      { id: 'h2', date: '2026-05-07T09:15:00', message: 'Premier entretien réalisé' },
    ],
  },
  {
    id: '7',
    company: 'Airtable',
    role: 'Product Manager',
    contractType: 'cdi',
    appliedAt: '2026-05-02',
    offerUrl: 'https://airtable.com/careers',
    status: 'sent',
    notes: '',
    history: [{ id: 'h1', date: '2026-05-02T10:00:00', message: 'Candidature envoyée' }],
  },
]
